### ISSUE TITLE
Wire.beginTransmission() should not be used with Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [Infineon/arduino-optiga-trust-x#2]
In the file "arduino-optiga-trust-x/src/optiga_trustx/pal_i2c_arduino.cpp", in the function `pal_i2c_read()` the `Wire.beginTransmission()` just before the `Wire.requestFrom()` may be removed. That is line 254 at the moment.
Explanation: [Common-mistakes#3](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#3)

**Comment by ayushev** [comment]
@Koepel Thank you very much!
