### ISSUE TITLE
No example related to DTLS  implementation, and dtls source .c files are also missing

### ISSUE THREAD

**Issue by faboulous1** [Infineon/arduino-optiga-trust-x#5]
I havent found, how can i perform mutual handshake using arduino. This is an important thing which needs to be implemented. Secondly i donot find .c files corresponding to OCP.h header files in src folder.

**Comment by ayushev** [comment]
Hi,
 the arduino library doesn't demonstrate on-chip authentication, as it requires a communication channel. As Arduino doesn't provide a unified API for such channels it's not possible to demonstrate it.
To try out on-chip DTLS or off-chip TLS please refer to this [application notes](https://github.com/Infineon/optiga-trust-x#application_notes):
1) [On-Chip DTLS example](https://github.com/Infineon/onchipdtls-optiga-trust-x)
2) [Off-Chip TLS example (mbedTLS)](https://github.com/Infineon/mbedTLS-optiga-trust-x)
