### ISSUE TITLE
IFX_OPTIGA_TrustX::deriveKey always returning error

### ISSUE THREAD

**Issue by faboulous1** [Infineon/arduino-optiga-trust-x#6]
I use setup() code from example (calculateSignVerifySign), without any changes.
Here is my code in loop: First i save a private key in the eSESSION_ID_1, later i use this as shared secred to derive a key, but i get following error code (0x 8001 000B‬) that means according to documentation Command or message out of sequence. I am using code directly from repo without any changes.
 
  uint32_t ts = 0;
/*
   * Generate a key pair and store private key inside the security chip
   */
  printGreen("Generate Key Pair ... ");
  ts = millis();
  ret = trustX.generateKeypair(pubKey, pubKeyLen, eSESSION_ID_1);
  ts = millis() - ts;
  if (ret) {
    printlnRed("Failed");
    while (true);
  }
  output_result("Public key", ts, pubKey, pubKeyLen);

 uint8_t random_seed [] = {
        0x61, 0xC7, 0xDE, 0xF9, 0x0F, 0xD5, 0xCD, 0x7A, 
        0x8B, 0x7A, 0x36, 0x41, 0x04, 0xE0, 0x0D, 0x82, 
        0x38, 0x46, 0xBF, 0xB7, 0x70, 0xEE, 0xBF, 0x8F, 
        0x40, 0x25, 0x2E, 0x0A, 0x21, 0x42, 0xAF, 0x9C,
};

  uint8_t  pkey[32];
 
  ret = trustX.deriveKey(random_seed, 32, pkey,  32);
  if (ret) {
    printlnRed("deriveKey Failed , ret : ");
    Serial.print(ret);
    while (true);
  }
  Serial.print(" Success Session key generated and stored in session id");
  

Here is the output on serial :

Initializing ... 
Begin to trust ... OK
OK
Generate Key Pair ... [OK] | Command executed in 125 ms
Public key Length: 68
Public key:
0x000000: 03 42 00 04 8b 0e fd f9 d6 5b 3a 5e 5c f4 ad cc .B.......[:^\...
0x000010: be 19 ff e7 7b 35 01 1b f8 a1 eb b2 89 91 31 b0 ....{5........1.
0x000020: a9 9f 76 66 35 c7 91 78 a2 7b e8 8d c1 b9 14 ab ..vf5..x.{......
0x000030: d9 46 81 71 14 26 8a d1 ae 50 52 36 18 a1 9c 0d .F.q.&...PR6....
0x000040: 93 07 05 49                                     ...I            
deriveKey Failed , ret : 
2147549195

**Comment by ayushev** [comment]
Hi, thanks for trying our library out.
The derive shared secret function is overloaded with different possible parameters, please have a look on the function definition. You need to specify from which Object ID should it generate a shared secret ( in you case this is a session id 1.
https://github.com/Infineon/arduino-optiga-trust-x/blob/master/src/OPTIGATrustX.h#L370

**Comment by faboulous1** [comment]
Hi, I am not using  sharedSecret function, as you can see in my code, i only did this
1- Generated a private key and stored it in SessionOID_1
2- Derived the key from it (if we see in the derive function we can see, it is using SessionOID1 to derive key)
Whats wrong? If i just created a private key and stored it in sessionId1 and then derive a key from it?

Why i am getting this error:  error code (0x 8001 000B‬)

**Comment by ayushev** [comment]
Because the command is called out of sequence, it's is not mentioned in the Arduino library, because the derive key function is private and not really adapted for the users. You can try to still make use of it by having the following sequence of commands (the c based examples are here just for you [reference](https://github.com/Infineon/optiga-trust-x/edit/master/examples/optiga/example_optiga_crypt_tls_prf_sha256.c.) Generate Keypair, Generate a shared secret then Derive a key, all functions should be called with the same session id number. I hope it helps.

**Comment by faboulous1** [comment]
The reference you have shared is broken link.

**Comment by faboulous1** [comment]
I have another question regarding usability of the OPTIGA chip library, may i know how can i send you that? Via email? As this is not the right place to ask that. May i know email?

**Comment by ayushev** [comment]
https://github.com/Infineon/optiga-trust-x/blob/master/examples/optiga/example_optiga_crypt_tls_prf_sha256.c

The email is: DSSTechnicalSupport@infineon.com

**Comment by ayushev** [comment]
Bit if the question is regarding the usability of the library you can ask either here or in the repository of the [software framework](https://github.com/Infineon/optiga-trust-x)

**Comment by faboulous1** [comment]
I have tried these steps and they worked: 1- GenerateKey 2- CalculateSharedSecret 3- DeriveKey.
My quesion is, why cant i derive key directly from GeneratedPrivateKey? Why i need to add sharedSecret step. As far as Optiga IC is concerned, it should run same algo on any data provided, is it due to lack of library implementation or is it restriction in hardware?

**Comment by ayushev** [comment]
This is a restriction of the 
The deriveKey command is implemented as TLS 1.2 PRF SHA256 function (deriveKey, [standard](http://tools.ietf.org/html/rfc5246#section-5)), which requires as an input a set of parameters, one of which is a shared secret (not a private key, generated by the ECDH operation (calculateSharedSecret), generation of the shared secret via ECDH isn’t possible without a keypair (generateKeypair)

**Comment by faboulous1** [comment]
Thats fine. But i guess we cannot use PrivateKey to generate sharedSecret? Why we cant use PrivateKey1 (which is pre generated) to generate a sharedSecret and then derive a key?

**Comment by ayushev** [comment]
You can do this as well.

I've modified the code [here](https://github.com/Infineon/arduino-optiga-trust-x/commit/14ceab8d3786354a203ba47b1870a6b7cd85ac85) you can try it, but you need to modify the deriveKey function as well, as this isn't part of the public API so far.

**Comment by faboulous1** [comment]
Ok. got it, this is better. 
I guess, we dont need to modify deriveKey, if we are storing the sharedSecret in sessionID1.
