### ISSUE TITLE
ECC 192bit

### ISSUE THREAD

**Issue by xATI-researcher** [Infineon/arduino-optiga-trust-x#9]
Hello. I am using Optiga in an Arduino based setup with low memory available. Is there a way to configure OptigaTrust X  in order to be able to generate keys based on ECC 192 bit?

**Comment by ayushev** [comment]
Hello @xATI-researcher ,

unfortunately the chip supports only regular NIST P curves with 256 bits and 384 bits keys.

**Comment by xATI-researcher** [comment]
Ok. Thank you.
